server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-swallow-size: 100MB

spring:
  application:
    name: JTL-WXAPP
  profiles:
    active: dev
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:
    username: root
    password: ${jlt.db.pw}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    org.springframework.web: DEBUG
    com.zsc: debug
    org.mybatis: DEBUG
    com.mysql.cj: DEBUG
#    org.hibernate: DEBUG
    org.mybatis.spring: DEBUG
#    org.apache.ibatis: DEBUG
    org.thymeleaf: DEBUG
  pattern:
    dateformat: HH:mm:ss:SSS
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    path: "logs/${spring.application.name}"

feign:
  okhttp:
    enabled: true

aliyun:
  oss:
    # oss对外服务的访问域名
    endpoint: 
    # 访问身份验证中用到用户标识
    accessKeyId: 
    # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    accessKeySecret: 
    # oss的存储空间
    bucketName: 
    # 上传文件大小(M)
    maxSize: 20
    # 上传文件夹路径前缀
    dir:
      prefix: picture/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zsc.wxapp.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

external:
  api:
    url: 

imgloc:
  upload:
    url: https://imgloc.com/api

api:
  local:
    url: http://localhost:8089

localimagesbed:
  port: 8088

pagehelper:
  reasonable: true
  helper-dialect: mysql
  support-methods-arguments: true
  page-size-zero: false

knife4j:
  enable: true
  openapi:
    title: 价利通微信小程序后端接口文档
    description: "前端接口文档"
    concat: 
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.hmall.controller

jlt:
  jwt:
    secret-key: 
    ttl: 
    token-name: JLT
