server:
  port: 8082
  servlet:
    context-path: /
spring:
  application:
    name: JLT-ExternalService
  main:
    allow-circular-references: true
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://172.16.18.59:3306/TobaccoPriceGuidance?serverTimezone=Asia/Shanghai&useUnicode=true&&characterEncoding=utf8
#    username: zsc
#    password: zsc2024
    url: jdbc:mysql://172.16.18.59:3307/ods?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: zsyc
    password: ZSyc!@#188..
#    cloud:
#      nacos:
#        server-addr:127.0.0.1:8848
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

external:
  api:
    url: http://172.16.18.59:8080/api/proxy/invoke

imgloc:
  upload:
    url: https://imgloc.com/api

aliyun:
  oss:
    # oss对外服务的访问域名
    endpoint: oss-cn-shenzhen.aliyuncs.com
    # 访问身份验证中用到用户标识
    accessKeyId: LTAI5tGX2dGDBsXU3kiiz4ip
    # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    accessKeySecret: mFIDCT4n5VA9EdozeYDUHRc6FjjRng
    # oss的存储空间
    bucketName: zsc9528
    # 上传文件大小(M)
    maxSize: 20
    # 上传文件夹路径前缀
    dir:
      prefix: picture/


api:
  local:
    url: http://localhost:8089


logging:
  level:
    org.springframework.web: DEBUG
    com.zsc: debug
    org.mybatis: DEBUG
    com.mysql.cj: DEBUG
    org.mybatis.spring: DEBUG
    org.thymeleaf: DEBUG
  pattern:
    dateformat: HH:mm:ss:SSS
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    path: "logs/${spring.application.name}"

pagehelper:
  reasonable: true
  helper-dialect: mysql
  support-methods-arguments: true
  page-size-zero: false
  params: count=countSql



